[logging]
level = "INFO"
prefix = "./"

[api]
host = "127.0.0.1"
port = 8088
public_url = "https://35b4f2de1c88.ngrok-free.app"
prefix_path = '/api/v1'
jwt_secret = '3VnIwL4yYreyayzHRMdALaGmiXzAkkkhaoyeE1J2yjpYaquu3qWsKIu6tlgPmHMl'
jwt_lifetime = '1 day'

[frontend]
title = "The Legends' Cookbook"
enable = true
prefix_path = '/gui'
storage_secret = '3VnIwL4yYreyayzHRMdALaGmiXzAkkkhaoyeE1J2yjpYaquu3qWsKIu6tlgPmHMl'

[telegram_bot]
enable = true
webhook_uri = "/telegram/webhook"
bot_link = 'https://t.me/legendsbutlerbot'
api_token = '8298478680:AAHyyMFCmc_hLhUZyI5awjhMPkt8eQAXMQM'
login_token_lifetime = '5 minute'

[database]
mode='sqlite'

[database.sqlite]
filename='locale.db'

[database.locale]
host='localhost'
port=3306
schema='srv1_locale'